PROG = ../../src/xduce.opt

test:
	@echo "Formatting a Netscape bookmarks file into the HTML format..."
	$(PROG) bookmarks.q -- bookmarks.html public.html
	@echo "Done.  See public.html."

clean:
	rm *~ public.html out.xml

