test:
	$(MAKE) -i -C addrbook test
	$(MAKE) -i -C bookmarks test
	$(MAKE) -i -C html2latex test
	$(MAKE) -i -C ns2xbel test
	$(MAKE) -i -C rng2xduce test
	$(MAKE) -i -C polysample test

clean:
	$(MAKE) -i -C addrbook clean
	$(MAKE) -i -C bookmarks clean
	$(MAKE) -i -C html2latex clean
	$(MAKE) -i -C ns2xbel clean
	$(MAKE) -i -C rng2xduce clean
	$(MAKE) -i -C xbel clean
	$(MAKE) -i -C xbel-demo clean
	$(MAKE) -i -C polysample clean


